import type { Metadata } from "next";

import "../styles/globals.css";
import { NavigationBar } from "@/components/navigation/NavigationBar";
import { Footer } from "@/components/Footer";
import { poppins, dmtext } from "@/lib/font";
import StoreProvider from "./StoreProvider";

export const metadata: Metadata = {
  title: "Moives-Tovies",
  description: "Generated by RodShopBd",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins} ${dmtext} bg-background text-primary-default antialiased`}
      >
        <StoreProvider>
          <NavigationBar />
          <main className="font-poppins pt-[4.5rem]">{children}</main>
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
